# Reference copy of the Homebrew cask.
#
# The authoritative cask lives in the mosaic-finance/homebrew-tap repo
# (github.com/mosaic-finance/homebrew-tap, Casks/ directory) and is
# auto-generated by goreleaser's `homebrew_casks:` config on every tagged
# release. The copy below mirrors the snapshot-generated cask and is kept
# here for documentation and review purposes only.
#
# Migrated from a formula (brew/Formula/) in Story 39.9: goreleaser fully
# deprecated `brews:` in v2.16 in favor of `homebrew_casks:`. Casks ship
# the pre-compiled binary directly; there is no `test do` block in the
# cask DSL.
#
# Operator checklist (see RELEASE_OPS_36_11.md section 4):
# 1. Create the public repo: github.com/mosaic-finance/homebrew-tap
# 2. Add HOMEBREW_TAP_GITHUB_TOKEN repo secret to mosaicss/archivist:
#    fine-grained PAT, `contents: read+write`, scoped to the tap repo only.
# Both must exist BEFORE the next tag is pushed: with publishing enabled,
# a missing repo or secret fails the release at the cask publish step.

cask "archivist" do
  version "GORELEASER_WILL_REPLACE"

  on_macos do
    sha256 "GORELEASER_WILL_REPLACE"
    url "https://github.com/mosaicss/archivist/releases/download/v#{version}/archivist_v#{version}_darwin_all.tar.gz"
  end

  # Homebrew >= 4.5 installs casks with Linux binaries on Linux too
  # (preliminary support). curl|sh remains the recommended Linux channel.
  on_linux do
    on_intel do
      sha256 "GORELEASER_WILL_REPLACE"
      url "https://github.com/mosaicss/archivist/releases/download/v#{version}/archivist_v#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "GORELEASER_WILL_REPLACE"
      url "https://github.com/mosaicss/archivist/releases/download/v#{version}/archivist_v#{version}_linux_arm64.tar.gz"
    end
  end

  name "archivist"
  desc "Archivist CLI for Mosaic filings research"
  homepage "https://mosaic-finance.com/products/archivist-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "archivist"

  postflight do
    # Strip the Gatekeeper quarantine flag. Release binaries are
    # unsigned until the operator provisions Apple notarization
    # (RELEASE_OPS_36_11.md section 2). macOS only: Homebrew >= 4.5
    # installs casks with Linux binaries on Linux too, where
    # /usr/bin/xattr does not exist and would abort the install.
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/archivist"]
    end
    # Fetch the matching Claude skill bundle when ~/.claude/skills
    # exists (same semantics as the pre-cask formula post_install).
    if File.directory?(File.expand_path("~/.claude/skills"))
      skill_dir = File.expand_path("~/.claude/skills/archivist")
      FileUtils.mkdir_p skill_dir
      system_command "/usr/bin/curl",
                     args: ["-fsSL", "-o", "/tmp/archivist-skill.tar.gz",
                            "https://github.com/mosaicss/archivist/releases/download/v#{version}/archivist_v#{version}_skill-bundle.tar.gz"]
      system_command "/usr/bin/tar",
                     args: ["-xzf", "/tmp/archivist-skill.tar.gz", "-C", skill_dir]
      FileUtils.rm_f "/tmp/archivist-skill.tar.gz"
    end
    # Stamp the install channel so `archivist update` routes users to
    # `brew upgrade` instead of self-replacing the binary.
    FileUtils.mkdir_p File.expand_path("~/.archivist")
    File.write File.expand_path("~/.archivist/install-channel"), "brew\n"
  end
end
